FROM almalinux:9
# CMD ["ping","google.com"] # can be overriden while running docker
# ENTRYPOINT ["ping","google.com"] # cannot be overriden while running docker
CMD ["google.com"]
ENTRYPOINT ["ping"]